baseURL = "http://hugoportfolio.flkdesign.com"
languageCode = "en-us"
title = "Batman Portfolio X Frederik Lee Kofoed"
theme = "ananke"
publishDir = "docs"


[params]
  favicon = ""
  description = "Batmans Portfolio by Frederik Lee Kofoed"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/imgs/batman_baggrund3.jpg"
  recent_posts_number = 2
  

[[menu.main]]
name                   = "Home"
weight                 = 10
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Portfolio"
weight                 = 20
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "About"
weight                 = 40
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Contact"
weight                 = 50
identifier             = "contact"
url                    = "/contact/"